# Generated by Django 4.2 on 2024-01-03 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MLModelData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iron_feed', models.FloatField()),
                ('silica_feed', models.FloatField()),
                ('starch_flow', models.FloatField()),
                ('amina_flow', models.FloatField()),
                ('ore_pulp_flow', models.FloatField()),
                ('ore_pulp_density', models.FloatField()),
                ('column_04_air_flow', models.FloatField()),
                ('column_05_air_flow', models.FloatField()),
                ('column_06_air_flow', models.FloatField()),
                ('column_07_air_flow', models.FloatField()),
                ('column_01_level', models.FloatField()),
                ('column_02_level', models.FloatField()),
                ('column_03_level', models.FloatField()),
                ('column_04_level', models.FloatField()),
                ('column_05_level', models.FloatField()),
                ('column_06_level', models.FloatField()),
                ('column_07_level', models.FloatField()),
            ],
        ),
    ]
